"""drop student_id_str from submissions

Revision ID: 6d66112284ff
Revises: 87a71ad6e099
Create Date: 2026-04-01 20:11:41.234888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d66112284ff'
down_revision: Union[str, Sequence[str], None] = '87a71ad6e099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'student_id_str')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('student_id_str', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
