"""add expected_answer and test_cases to tasks

Revision ID: 87a71ad6e099
Revises: 6a15baafa199
Create Date: 2026-04-01 18:17:07.577163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a71ad6e099'
down_revision: Union[str, Sequence[str], None] = '6a15baafa199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('expected_answer', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('test_cases', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'test_cases')
    op.drop_column('tasks', 'expected_answer')
    # ### end Alembic commands ###
