"""add template_filename and template_content to assignments

Revision ID: ea1a137b6532
Revises: 6d66112284ff
Create Date: 2026-04-03 14:47:04.088641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1a137b6532'
down_revision: Union[str, Sequence[str], None] = '6d66112284ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('template_filename', sa.String(), nullable=True))
    op.add_column('assignments', sa.Column('template_content', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'template_content')
    op.drop_column('assignments', 'template_filename')
    # ### end Alembic commands ###
